name: 'Delete workflow runs'
description: 'An action to delete workflow runs in a repository.'
author: 'Bright Ran'

inputs:
  token:
    description: 'The token used to authenticate.'
    required: true
    default: ${{ github.token }}

  repository:
    description: 'The name of the repository.'
    required: true
    default: ${{ github.repository }}
  
  workflow_name:
    description: 'The name of the repository.'
    required: true
    default: ${{ github.workflow }}

  retain_days:
    description: 'The number of days.'
    required: true
    default: 90

  keep_minimum_runs:
    description: 'The minimum runs to keep for each workflow.'
    required: true
    default: 6

  workflow_file_name:
    description: 'The workflow file name.'
    required: true
    default: ""
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'delete'
  color: 'red'
